language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

before_install:
  - pip install pycodestyle
install:
  - sh install.sh
script:
  - sh test.sh
  - find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +